version: '3.9'

services:
  nango-db:
    image: 'postgres:16.0-alpine'
    container_name: nango-db
    environment:
      POSTGRES_PASSWORD: nango
      POSTGRES_USER: nango
      POSTGRES_DB: nango
    ports:
      - '15435:5432'
    volumes:
      - './nango-data:/var/lib/postgresql/data'
    networks:
      - nango
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nango -d nango']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nango-server:
    image: 'nangohq/nango-server:hosted'
    container_name: nango-server
    platform: linux/amd64
    environment:
      - NANGO_ENCRYPTION_KEY
      - NANGO_DB_USER=nango
      - NANGO_DB_PASSWORD=nango
      - NANGO_DB_HOST=nango-db
      - NANGO_DB_NAME=nango
      - NANGO_DB_SSL=false
      - NANGO_DB_ADDITIONAL_SCHEMAS
      - NANGO_DB_POOL_MIN=2
      - NANGO_DB_POOL_MAX=10
      - RECORDS_DATABASE_URL=postgresql://nango:nango@nango-db:5432/nango
      - SERVER_PORT=3003
      - CSP_REPORT_ONLY=true
      - NANGO_SERVER_URL=https://nango.csa.competera.com
      - NANGO_PUBLIC_SERVER_URL=https://nango.csa.competera.com
      - FLAG_AUTH_ENABLED=true
      - NANGO_DASHBOARD_USERNAME=admin
      - NANGO_DASHBOARD_PASSWORD=changeme
      - LOG_LEVEL=info
      - FLAG_SERVE_CONNECT_UI=true
    volumes:
      - './packages/providers/providers.yaml:/app/packages/providers/providers.yaml'
    restart: always
    ports:
      - '3003:3003'
      - '3009:3009'
    depends_on:
      - nango-db
    healthcheck:
      test: ['CMD', 'true']
    labels:
      - traefik.enable=true

      # Dashboard (production)
      - traefik.http.routers.nango.rule=Host(`nango.csa.competera.com`)
      - traefik.http.routers.nango.entrypoints=https
      - traefik.http.routers.nango.tls.certresolver=letsencrypt
      - traefik.http.routers.nango.service=nango-server
      - traefik.http.services.nango-server.loadbalancer.server.port=3003

      # Connect UI (production)
      - traefik.http.routers.nango-connect.rule=Host(`nango-connect.csa.competera.com`)
      - traefik.http.routers.nango-connect.entrypoints=https
      - traefik.http.routers.nango-connect.tls.certresolver=letsencrypt
      - traefik.http.routers.nango-connect.service=nango-server-connect
      - traefik.http.services.nango-server-connect.loadbalancer.server.port=3009
    networks:
      coolify:
        aliases:
          - nango-server
      cc44gwwc0ss4sc0w40g8ckgg:
        aliases:
          - nango-server

  nango-redis:
    image: redis:7.2.4
    container_name: nango-redis
    ports:
      - '16379:6379'
    networks:
      - nango
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  nango:
    driver: bridge
  coolify:
    external: true
  cc44gwwc0ss4sc0w40g8ckgg:
    external: true

volumes:
  elasticsearch-data1:
    driver: local
