version: '3.9'

services:
  nango-db:
    image: postgres:16.0-alpine
    container_name: nango-db
    environment:
      POSTGRES_PASSWORD: nango
      POSTGRES_USER: nango
      POSTGRES_DB: nango
    volumes:
      - nango-db-data:/var/lib/postgresql/data
    networks:
      - nango

  nango-server:
    image: nangohq/nango-server:hosted
    container_name: nango-server
    platform: linux/amd64
    depends_on:
      - nango-db
      - nango-redis
    environment:
      NANGO_ENCRYPTION_KEY: ${NANGO_ENCRYPTION_KEY}
      NANGO_DB_USER: nango
      NANGO_DB_PASSWORD: nango
      NANGO_DB_HOST: nango-db
      NANGO_DB_NAME: nango
      RECORDS_DATABASE_URL: postgresql://nango:nango@nango-db:5432/nango
      SERVER_PORT: 3003
      CONNECT_UI_PORT: 3009
      NANGO_SERVER_URL: https://nango.csa.competera.com
      NANGO_PUBLIC_SERVER_URL: https://nango.csa.competera.com
      NANGO_DASHBOARD_USERNAME: ${NANGO_DASHBOARD_USERNAME}
      NANGO_DASHBOARD_PASSWORD: ${NANGO_DASHBOARD_PASSWORD}
      LOG_LEVEL: info
      FLAG_SERVE_CONNECT_UI: 'true'
    labels:
        - traefik.enable=true

        # Dashboard
        - traefik.http.routers.nango-dashboard.rule=Host(`nango.csa.competera.com`)
        - traefik.http.routers.nango-dashboard.entrypoints=web
        - traefik.http.routers.nango-dashboard.tls.certresolver=letsencrypt
        - traefik.http.routers.nango-dashboard.service=nango-dashboard-service
        - traefik.http.services.nango-dashboard-service.loadbalancer.server.port=3003

        # Connect UI
        - traefik.http.routers.nango-connect.rule=Host(`nango.csa.competera.com`) && PathPrefix(`/connect`)
        - traefik.http.routers.nango-connect.entrypoints=web
        - traefik.http.routers.nango-connect.tls.certresolver=letsencrypt
        - traefik.http.routers.nango-connect.service=nango-connect-service
        - traefik.http.services.nango-connect-service.loadbalancer.server.port=3009
    volumes:
      - ./packages/providers/providers.yaml:/app/packages/providers/providers.yaml
    restart: always
    networks:
      - nango

  nango-redis:
    image: redis:7.2.4
    container_name: nango-redis
    ports:
      - '6382:6379'
    networks:
      - nango

networks:
  nango:

volumes:
  nango-db-data:
    driver: local